=== Seynabou-Diop/ServiceMessagerie/modelisation/messagerie.dtd
<!ELEMENT serviceMessagerie (utilisateurs)>

<!ELEMENT utilisateurs (utilisateur+)>

<!ELEMENT utilisateur (contacts, Groupes, discussions, appels)>
<!ATTLIST utilisateur
    id ID #REQUIRED
    nom CDATA #REQUIRED
    numero CDATA #REQUIRED
    statut (Offline | Online) #REQUIRED
    photo CDATA #REQUIRED>


<!ELEMENT contacts (contact*)>

<!ELEMENT contact (commonGroups*)>
<!ATTLIST contact
    id IDREF #REQUIRED
>

<!ELEMENT photo (#PCDATA)>

<!ELEMENT commonGroups (commonGroup+)>
<!ELEMENT commonGroup EMPTY>
<!ATTLIST commonGroup id IDREF #REQUIRED>

<!ELEMENT Groupes (Groupe*)>
<!ELEMENT Groupe (membres)>
<!ATTLIST Groupe id ID #REQUIRED
          nom CDATA #REQUIRED
          description CDATA #REQUIRED
          nombreMembres CDATA #REQUIRED
>


<!ELEMENT membres (membre+)>

<!ELEMENT membre EMPTY>
<!ATTLIST membre id IDREF #REQUIRED>

<!ELEMENT discussions (discussion*)>

<!ELEMENT discussion (discuGroupe?,correspondant?,infoGroupe?, messages)>
<!ATTLIST discussion
    categorie (individuelle | groupe) #REQUIRED
    id ID #REQUIRED
>

<!ELEMENT discuGroupe EMPTY>
<!ATTLIST discuGroupe id IDREF #REQUIRED
>

<!ELEMENT correspondant EMPTY>
<!ATTLIST correspondant id IDREF #REQUIRED
>



<!ELEMENT messages (message*)>

<!ELEMENT message (contenu, citation?)>
<!ATTLIST message
    id ID #REQUIRED
    expediteur IDREF #REQUIRED
    type CDATA #REQUIRED
    timestamp CDATA #REQUIRED
>

<!ELEMENT contenu (texte?, fichier?, vocal?)>

<!ELEMENT texte (#PCDATA)>
<!ELEMENT fichier (#PCDATA)>
<!ELEMENT vocal EMPTY>
<!ATTLIST vocal
    minutes CDATA #REQUIRED
    secondes CDATA #REQUIRED
>

<!ELEMENT citation EMPTY>
<!ATTLIST citation message IDREF #REQUIRED
>

<!ELEMENT appels (appel*)>

<!ELEMENT appel (correspondant?,membres?, duree)>
<!ATTLIST appel
    id   ID #REQUIRED
    type CDATA #REQUIRED
    categorie CDATA #REQUIRED
    chiffre (true | false) #REQUIRED
>


<!ELEMENT duree EMPTY>
<!ATTLIST duree
    heures CDATA #REQUIRED
    minutes CDATA #REQUIRED
>

=== Seynabou-Diop/ServiceMessagerie/modelisation/serviceMessagerie.xml
<?xml version="1.0" encoding="UTF-8"?>
 <serviceMessagerie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="messagerie.xsd"> 
<!-- <!DOCTYPE serviceMessagerie SYSTEM "messagerie.dtd"> 

<serviceMessagerie> -->
    <utilisateurs> 
        <utilisateur id="u1" nom="Lamoth Mboup" numero="7711122" statut="Online" photo="lamoth.jpg">
            <contacts>
                <contact id="u1">
                  <commonGroups>
                    <commonGroup id="g1"/>
                    <commonGroup id="g2"/>
                  </commonGroups>
                </contact>
                <contact id="u3">
                    <commonGroups>
                        <commonGroup id="g1"/>
                    </commonGroups>   
                </contact>
            </contacts>

            <Groupes>
                <Groupe id="g1" nom="les anciens de l'esp" description="ce groupe regroupe les alumnis de l'esp" nombreMembres="3">
                    <membres>
                        <membre id="u1" />
                        <membre id="u2" />
                        <membre id="u3"/>
                    </membres>
                </Groupe>
                <Groupe id="g2" nom="otakus" description="manga life" nombreMembres="3">
                    <membres>
                        <membre id="u2" />
                        <membre id="u1" />
                        <membre id="u3"/>
                    </membres>
                </Groupe>
            </Groupes>

            <discussions>
                <discussion categorie="individuelle" id="d1">
                    <correspondant id="u3"/>
                    <messages>
                        <message id="m1" expediteur="u3" type="texte" timestamp="2023-06-26T10:00:00">
                            <contenu>
                                <texte>Salut comment vas-tu??</texte>    
                            </contenu>
                        </message>
                        <message id="m2" expediteur="u1" type="texte" timestamp="2023-06-26T10:05:00">
                            <contenu>
                                <texte>Bien et toi?</texte>
                            </contenu>
                            <citation message="m1"/>
                        </message>
                    </messages>
                </discussion>

                <discussion categorie="individuelle" id="d2">
                    <correspondant id="u2"/>
                    <messages>
                        <message id="m3" expediteur="u2" type="texte" timestamp="2023-06-26T10:00:00">
                            <contenu>
                                <texte>Bonjour tu n'as pas oublie notre reunion.</texte>   
                            </contenu>
                        </message>
                        <message id="m4" expediteur="u1" type="texte" timestamp="2023-06-26T10:10:00">
                            <contenu>
                                <texte>Non j'ai pas oublie</texte>
                            </contenu>
                        </message>
                        <message id="m5" expediteur="u2" type="vocal" timestamp="2023-06-26T10:10:00">
                            <contenu>
                               <vocal minutes="00" secondes="15" />
                            </contenu>
                            <citation message="m4"/>
                        </message>
                    </messages>
                </discussion>
                
                <discussion categorie="groupe" id="d3">
                    <discuGroupe id="g1"/>
                    <messages>
                        <message id="m6" expediteur="u3" type="texte" timestamp="2023-06-26T10:10:00">
                            <contenu>
                                <texte>Salut, quelqu'un pour m'envoyer le projet de xml</texte>
                            </contenu>
                        </message>
                        <message id="m7" expediteur="u2" type="fichier" timestamp="2023-06-2T11:10:00">
                            <contenu>
                                <fichier>/home/lamoth/Bureau/projetxml.pdf</fichier>
                            </contenu>
                            <citation message="m7"/>
                        </message>
                    </messages>
                </discussion>
        </discussions>
        <appels>
                <appel id="a1" type="vocal" categorie="groupe" chiffre="true">
                    <membres>
                        <membre id="u2" />
                        <membre id="u3"/>
                    </membres>
                    <duree heures="00" minutes="15" />
                </appel>
                <appel id="a2" type="vocal" categorie="individuelle" chiffre="true">
                    <correspondant id="u2" />
                    <duree heures="00" minutes="15" />
                </appel>
                <appel id="a3" type="video" categorie="groupe" chiffre="true">
                    <membres>
                        <membre id="u2" />
                        <membre id="u3"/>
                    </membres>
                    <duree heures="01" minutes="15" />
                </appel>
                <appel id="a4" type="video" categorie="individuelle" chiffre="true">
                    <correspondant id="u3" />
                    <duree heures="00" minutes="15" />
                </appel>
            </appels>
        </utilisateur>

        <utilisateur id="u2" nom="Oumar Sene" numero="7745098" statut="Online" photo="oumar.jpeg">
            <contacts>
                <contact id="u1">
                  <commonGroups>
                    <commonGroup id="g2"/>
                  </commonGroups>
                </contact>
                <contact id="u3" >
                    <commonGroups>
                        <commonGroup id="g2"/>
                    </commonGroups>
                </contact>
            </contacts>

            <Groupes></Groupes>

            <discussions>
                <discussion categorie="individuelle" id="d4">
                    <correspondant id="u3"/>
                    <messages>
                        <message id="m8" expediteur="u3" type="texte" timestamp="2023-06-26T10:00:00">
                            <contenu>
                                <texte>Salut comment vas-tu??</texte>    
                            </contenu>
                        </message>
                        <message id="m9" expediteur="u1" type="texte" timestamp="2023-06-26T10:05:00">
                            <contenu>
                                <texte>Bien et toi?</texte>
                            </contenu>
                            <citation message="m8"/>
                        </message>
                    </messages>
                </discussion>
                <discussion categorie="groupe" id="d5">
                    <messages></messages>
                </discussion>
            </discussions>
            <appels>
                    <appel id="a5" type="vocal" categorie="groupe" chiffre="true">
                        <membres>
                            <membre id="u1" />
                            <membre id="u2" />
                            <membre id="u3"/>
                        </membres>
                        <duree heures="00" minutes="15" />
                    </appel>
            </appels>
        </utilisateur>

        <utilisateur id="u3" nom="Fama Diop" numero="7567789" statut="Online" photo="fama.jpeg">
            <contacts>
                <contact id="u1">
                    <commonGroups>
                        <commonGroup id="g1"/>
                    </commonGroups>
                </contact>
                <contact id="u2">
                </contact>
            </contacts>
            <Groupes></Groupes>

            <discussions>
                <discussion categorie="individuelle" id="d6">
                    <correspondant id="u1"/>
                    <messages>
                        <message id="m10" expediteur="u1" type="texte" timestamp="2023-06-26T10:00:00">
                            <contenu>
                                <texte>Salut comment ça va ?</texte>
                            </contenu>
                        </message>
                        <message id="m11" expediteur="u3" type="texte" timestamp="2023-06-26T10:05:00">
                            <contenu>
                                <texte>Ça va bien, merci !</texte>
                            </contenu>
                            <citation message="m10"/>
                        </message>
                    </messages>
                </discussion>

            </discussions>
            <appels>
                <appel id="a6" type="vocal" categorie="groupe" chiffre="true">
                    <membres>
                        <membre id="u2"/>
                        <membre id="u1"/>
                    </membres>
                    <duree heures="00" minutes="15"/>
                </appel>
            </appels>
        </utilisateur>

    </utilisateurs>
</serviceMessagerie>
